// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_email from "./email.sync.ts";
import * as sync_authenticated_routes from "./authenticated_routes.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_email)) {
  if (typeof func === "function") {
    allSyncs[`email.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_authenticated_routes)) {
  if (typeof func === "function") {
    allSyncs[`authenticated_routes.${name}`] = func as Sync;
  }
}

export default allSyncs;
